# docker-compose config
address = "core:8080"
strapath = "./dist/"

[db]
host = "localhost"
port = 27017

[redis]
host = "core"
port = 6379

[executors]
    [executors.python]
    type = "python"
    host = "python"
    port = 5000



[tasks]
    [tasks.open]
    event = "emit_open"
    spec = "0 5 9 * * *"

    [tasks.close]
    event = "emit_close"
    spec =  "0 0 16 * * *"